### PR TITLE
Ported VanillaTransform to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by izaruba**
The code is isolated in `./DotNetCore` folder
- VanillaTransform.Core is implemented as Shared Project
- Added an ability to create .NET Core global tool (https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)

(!) IMPORTANT NOTE
NUnit test framework is replaced with xUnit

### CODE REVIEW

**Comment by cezarypiatek** [comment]
Hi

Thanks for the PR, but I have a main remark: why did you duplicate the all codebase?

**Comment by izaruba** [comment]
I was working with the two solutions, and will probably do if there's something to be changed, so I decided to keep them both without intersection until you decide if the solution I made fits the goal.
If you think it would be better to replace the origin code base, I will do it.

**Comment by cezarypiatek** [comment]
I have a very busy week, please give a few days to review these changes.

**Comment by cezarypiatek** [comment]
Sorry for the delay.

First of all, you have to get rid of the code duplication because it's almost impossible to track what really has been changed. Besides that there are a missing parts:

- VaniilaTransformer - it should be a multi-target project with targets set for net461 and netstandard2.0
- VanillaTransformer.Console - this project should produce `exe` application
- nuget package should contains both VanillaTransformer versions: net461 and netstandard2.0
- `\Nuget\build\VanillaTransformer.targets` should be modified to load appropriate dll task depending on the currently used tool: `msbuild` or `dotnet msbuild` (as it was described in Nate McMaster article referenced in #8)

**Comment by izaruba** [comment]
Thank you for you feedback.
I will make the required changes.

**Comment by cezarypiatek** [comment]
This was fixed with #12

**Pull request closed without merging**
